# 定义服务列表
services:

  # OpenList 服务配置
  openlist:
    # 使用毫秒镜像源的 latest 版本
    image: docker.1ms.run/openlistteam/openlist:latest
    # 容器名称设为 openlist
    container_name: openlist
    # 依赖 qbittorrentee 和 aria2 服务
    depends_on:
        - qbittorrentee
        - aria2
    # 环境变量配置
    environment:
        # 用户 ID 设为 root
        - PUID=0
        # 用户组 ID 设为 root
        - PGID=0
        # 文件权限掩码设为 022
        - UMASK=022
        # 时区设为上海
        - TZ=Asia/Shanghai
    # 端口映射 5233:5244
    ports:
        - 5233:5244
    # 数据卷配置
    volumes:
        # 挂载本地 list/data 目录到容器数据目录
        - ./list/data:/opt/openlist/data
        # 共享 qBittorrent 临时目录
        - ./data/temp/qBittorrent:/opt/openlist/data/temp/qBittorrent
        # 共享 aria2 临时目录
        - ./data/temp/aria2:/opt/openlist/data/temp/aria2
    # 容器退出时自动重启（除非手动停止）
    restart: unless-stopped
    
  # qBittorrentEE 服务配置
  qbittorrentee:
    # 使用毫秒镜像源的最新版
    image: docker.1ms.run/superng6/qbittorrentee:latest
    # 容器名称设为 qbittorrentee
    container_name: qbittorrentee
    # 环境变量配置
    environment:
      # 用户 ID 设为 root
      - PUID=0
      # 用户组 ID 设为 root
      - PGID=0
      # 时区设为上海
      - TZ=Asia/Shanghai
      # WebUI 端口设为 6699
      - WEBUIPORT=6699
      # 启用下载权限修复
      - ENABLE_DOWNLOADS_PERM_FIX=true
    # 数据卷配置
    volumes:
      # 挂载配置目录
      - ./qbittorrentee/config:/config
      # 挂载下载目录
      - ./qbittorrentee/downloads:/downloads
      # 共享临时目录给 OpenList
      - ./data/temp/qBittorrent:/opt/openlist/data/temp/qBittorrent
    # 端口映射配置
    ports:
      # TCP 端口 6881（BT 协议）
      - 6881:6881
      # UDP 端口 6881（DHT 网络）
      - 6881:6881/udp
      # WebUI 端口 6699
      - 6699:6699
    # 容器退出时自动重启（除非手动停止）
    restart: unless-stopped

  # Aria2 离线下载服务配置
  aria2:
    # 使用毫秒镜像源的最新版
    image: docker.1ms.run/p3terx/aria2-pro:latest
    # 容器名称设为 aria2
    container_name: aria2
    # 环境变量配置
    environment:
      # 用户 ID 设为 root
      - PUID=0
      # 用户组 ID 设为 root
      - PGID=0
      # 时区设为上海
      - TZ=Asia/Shanghai
      # RPC 密钥 (请更改为自己的密钥)
      - RPC_SECRET=123456789Li
      # 启用磁盘缓存
      - DISK_CACHE=128M
      # 最大同时下载数
      - MAX_CONCURRENT_DOWNLOADS=5
    # 端口映射
    ports:
      # Aria2 RPC 端口
      - 6800:6800
      # Aria2 下载端口
      - 6888:6888
      # Aria2 下载端口 UDP
      - 6888:6888/udp
    # 数据卷配置
    volumes:
      # 配置目录
      - ./aria2/config:/config
      # 下载目录
      - ./aria2/downloads:/downloads
      # 共享临时目录
      - ./data/temp/aria2:/opt/openlist/data/temp/aria2
    # 容器退出时自动重启（除非手动停止）
    restart: unless-stopped

  # Aria2 WebUI (AriaNg) 服务配置
  ariang:
    # 使用毫秒镜像源的最新版
    image: docker.1ms.run/p3terx/ariang:latest
    # 容器名称设为 ariang
    container_name: ariang
    # 环境变量配置
    environment:
      # 用户 ID 设为 root
      - PUID=0
      # 用户组 ID 设为 root
      - PGID=0
      # 时区设为上海
      - TZ=Asia/Shanghai
    # 端口映射
    ports:
      # WebUI 访问端口
      - 6880:6880
    # 依赖 aria2 服务
    depends_on:
      - aria2
    # 容器退出时自动重启（除非手动停止）
    restart: unless-stopped