version: "3.8"  

services:  
# Aria2-Pro服务配置
 aria2-pro:
   # 设置容器名称
   container_name: aria2-pro            
   # 指定使用的镜像
   image: p3terx/aria2-pro             
   environment:
     # 设置进程用户ID（root）
     - PUID=0                          
     # 设置进程组ID（root）
     - PGID=0                          
     # 设置新建文件的权限掩码
     - UMASK_SET=022                   
     # 设置RPC访问密钥，建议修改为更复杂的密码
     - RPC_SECRET=123456               
     # 设置RPC服务端口
     - RPC_PORT=6800                   
     # 设置BT/DHT监听端口
     - LISTEN_PORT=6888                
     # 设置磁盘缓存大小
     - DISK_CACHE=64M                  
     # 是否启用IPv6模式
     - IPV6_MODE=false                 
     # 是否自动更新BT服务器
     - UPDATE_TRACKERS=true            
     # 可选的自定义Tracker服务器URL
     - CUSTOM_TRACKER_URL=             
     # 设置容器时区
     - TZ=Asia/Shanghai                
     # 启用rclone集成模式
     - SPECIAL_MODE=rclone             
   volumes:
     # 挂载配置文件目录
     - ./aria2-config:/config          
     # 挂载下载文件存储目录
     - /mnt/data/alist:/downloads      
     # 与Alist共享的临时目录
     - /mnt/data/alist:/opt/alist/data/temp  
   # 使用主机网络模式，方便直接使用主机端口
   network_mode: host                  
   # 容器异常退出时自动重启
   restart: unless-stopped             
   # 设置日志相关配置
   logging:                            
     driver: json-file
     options:
       max-size: 1m                    

# AriaNg Web界面服务配置
 ariang:
   # 设置容器名称
   container_name: ariang              
   # 指定使用的镜像
   image: p3terx/ariang               
   # 设置启动参数：指定端口和IPv6支持
   command: --port 6880 --ipv6        
   # 使用主机网络模式
   network_mode: host                 
   # 容器异常退出时自动重启
   restart: unless-stopped            
   # 设置日志相关配置
   logging:                           
     driver: json-file
     options:
       max-size: 1m                   

# qBittorrent服务配置
 qbittorrent:
   # 指定使用的镜像
   image: lscr.io/linuxserver/qbittorrent:latest  
   # 设置容器名称
   container_name: qbittorrent        
   environment:
     # 设置进程用户ID（root）
     - PUID=0                        
     # 设置进程组ID（root）
     - PGID=0                        
     # 设置容器时区
     - TZ=Asia/Shanghai              
     # 设置Web界面端口
     - WEBUI_PORT=8080              
     # 设置BT传输端口
     - TORRENTING_PORT=6881         
   volumes:
     # 挂载配置文件目录
     - ./qbittorrent-config:/config  
     # 挂载下载文件存储目录
     - /mnt/data/alist:/downloads    
     # 与Alist共享的临时目录
     - /mnt/data/alist:/opt/alist/data/temp  
   ports:
     # Web管理界面端口映射
     - 8080:8080                    
     # BT数据传输TCP端口映射
     - 6881:6881                    
     # BT数据传输UDP端口映射
     - 6881:6881/udp                
   # 容器异常退出时自动重启
   restart: unless-stopped          
   # 设置日志相关配置
   logging:                         
     driver: json-file
     options:
       max-size: 1m                 

# 重要提示：
# 1. 确保 /mnt/data/alist 目录已创建且有正确的读写权限
# 2. qBittorrent首次登录信息：用户名admin 密码adminadmin
# 3. Aria2 RPC密钥默认为123456，建议修改为更安全的密码