# 随机生成一个密码
# docker exec -it alist ./alist admin random
# 手动设置一个密码,`NEW_PASSWORD`是指你需要设置的密码
# docker exec -it alist ./alist admin set NEW_PASSWORD

# 设置目录权限 
# chmod -R 755 /mnt/usb

# Docker Compose 文件版本
version: "3.8"

services:
  # Alist 网盘服务
  alist:
    # 使用最新版 Alist 镜像
    image: xhofe/alist:latest
    # 容器名称
    container_name: alist
    # 端口映射：宿主机5244端口映射到容器5244端口
    ports:
      - 5233:5244
    # 容器运行环境配置
    environment:
      # 用户ID和组ID设置，0表示root用户
      - PUID=0
      - PGID=0
      # 文件权限掩码
      - UMASK=022
    # 总是重启
    restart: always
    # 挂载卷配置
    volumes:
      # Alist 数据目录
      - /mnt/usb/alist/data:/opt/alist/data
      # Aria2 临时文件目录
      - /mnt/usb/aria2/temp/aria2:/opt/alist/data/temp/aria2
      # 下载目录
      - /mnt/usb/aria2/temp/downloads:/downloads
      # 网盘根目录
      - /mnt/usb:/nas
    # 依赖 aria2-pro 服务，确保 aria2 先启动
    depends_on:
      aria2-pro:
        condition: "service_healthy"

  # Aria2 下载服务
  aria2-pro:
    container_name: aria2-pro
    # 使用 Aria2 Pro 镜像
    image: p3terx/aria2-pro
    # 运行环境配置
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      # RPC 密钥，用于连接验证
      - RPC_SECRET=123456
      # RPC 端口
      - RPC_PORT=6800
      # 监听端口
      - LISTEN_PORT=6888
      # 磁盘缓存大小
      - DISK_CACHE=64M
      # IPv6 模式
      - IPV6_MODE=false
      # 自动更新 Tracker
      - UPDATE_TRACKERS=true
      # 时区
      - TZ=Asia/Shanghai
      # 特殊模式：下载完成后自动移动文件
      - SPECIAL_MODE=move
    # 数据卷挂载
    volumes:
      # Aria2 配置目录
      - /mnt/usb/aria2/config:/config
      # Aria2 临时文件目录
      - /mnt/usb/aria2/temp/aria2:/opt/alist/data/temp/aria2
      # 下载临时目录
      - /mnt/usb/aria2/temp/downloads:/downloads
      # 下载完成目录
      - /mnt/usb/downloads:/completed
    # 端口映射
    ports:
      # RPC 端口
      - 6800:6800
      # 下载监听端口（TCP）
      - 6888:6888
      # 下载监听端口（UDP）
      - 6888:6888/udp
    # 除非手动停止，否则始终重启
    restart: unless-stopped
    # 日志配置
    logging:
      driver: json-file
      options:
        # 日志文件最大1M
        max-size: 1m
    # 健康检查
    healthcheck:
      # 通过 curl 检查 Aria2 RPC 服务是否正常
      test: ["CMD-SHELL", "curl -s -f -X POST -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"aria2.getVersion\",\"params\":[\"token:'$ARIA2_RPC_SECRET'\"]}' http://localhost:6800/jsonrpc || exit 1"]
      # 检查间隔
      interval: 30s
      # 超时时间
      timeout: 10s
      # 重试次数
      retries: 3

  # AriaNg Web 管理界面
  ariang:
    container_name: ariang
    # AriaNg 镜像
    image: p3terx/ariang
    # 启动命令，指定端口和 IPv6
    command: --port 6880 --ipv6
    # 端口映射
    ports:
      - 6880:6880
    # 除非手动停止，否则始终重启
    restart: unless-stopped
    # 日志配置
    logging:
      driver: json-file
      options:
        # 日志文件最大1M
        max-size: 1m